# Generated by Django 4.1.1 on 2022-10-05 01:02

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(default="", max_length=2),
        ),
        migrations.AddField(
            model_name="profile",
            name="degree",
            field=models.CharField(
                choices=[
                    ("--", "-----"),
                    ("B", "Bachelors Program (BS)"),
                    ("M", "Masters Program (MS)"),
                    ("P", "Post Docterate (PHD)"),
                ],
                default="--",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="diet",
            field=models.CharField(
                choices=[("--", "-----"), ("V", "Veg"), ("NV", "Non Veg")],
                default="--",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    ("--", "-----"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                default="--",
                max_length=5,
            ),
        ),
    ]
