# Generated by Django 4.1.1 on 2022-10-09 03:44

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                default="default.jpg", upload_to="profile_pics"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_country",
            field=django_countries.fields.CountryField(
                blank=True, default="No Preference", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_course",
            field=models.CharField(
                choices=[
                    ("N/A", "No Preference"),
                    ("CS", "Computer Science"),
                    ("CE", "Computer Engg."),
                    ("EE", "Electrical Engg."),
                    ("MEC", "Mechanical Engg."),
                ],
                default="N/A",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_degree",
            field=models.CharField(
                choices=[
                    ("N/A", "No Preference"),
                    ("B", "Bachelors Program (BS)"),
                    ("M", "Masters Program (MS)"),
                    ("P", "Post Docterate (PHD)"),
                ],
                default="N/A",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_diet",
            field=models.CharField(
                choices=[
                    ("N/A", "No Preference"),
                    ("V", "Veg"),
                    ("NV", "Non Veg"),
                ],
                default="N/A",
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_gender",
            field=models.CharField(
                choices=[
                    ("N/A", "No Preference"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                default="N/A",
                max_length=5,
            ),
        ),
    ]
