# Generated by Django 4.1.1 on 2022-10-09 03:11

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Computer Science", "Computer Science"),
                    ("Computer Engineering", "Computer Engg."),
                    ("Electrical Engineering", "Electrical Engg."),
                    ("Mechanical Engineering", "Mechanical Engg."),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Bachelors", "Bachelors Program (BS)"),
                    ("Masters", "Masters Program (MS)"),
                    ("Phd", "Post Docterate (PHD)"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="diet",
            field=models.CharField(
                blank=True,
                choices=[("Veg", "Veg"), ("Non-Veg", "Non Veg")],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_country",
            field=django_countries.fields.CountryField(
                blank=True, default="No Preference", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_course",
            field=models.CharField(
                choices=[
                    ("No Preference", "No Preference"),
                    ("Computer Science", "Computer Science"),
                    ("Computer Engineering", "Computer Engg."),
                    ("Electrical Engineering", "Electrical Engg."),
                    ("Mechanical Engineering", "Mechanical Engg."),
                ],
                default="No Preference",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_degree",
            field=models.CharField(
                choices=[
                    ("No Preference", "No Preference"),
                    ("Bachelors", "Bachelors Program (BS)"),
                    ("Masters", "Masters Program (MS)"),
                    ("Phd", "Post Docterate (PHD)"),
                ],
                default="No Preference",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_diet",
            field=models.CharField(
                choices=[
                    ("No Preference", "No Preference"),
                    ("Veg", "Veg"),
                    ("Non-Veg", "Non Veg"),
                ],
                default="No Preference",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_gender",
            field=models.CharField(
                choices=[
                    ("No Preference", "No Preference"),
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Other", "Other"),
                ],
                default="No Preference",
                max_length=128,
            ),
        ),
    ]
