# Generated by Django 4.1.1 on 2022-10-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0002_alter_customuser_first_name_alter_customuser_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="diet",
            field=models.CharField(
                blank=True,
                choices=[("Vegetarian", "Veg"), ("Non Vegetarian", "Non Veg")],
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_diet",
            field=models.CharField(
                choices=[
                    ("No Preference", "No Preference"),
                    ("Vegetarian", "Veg"),
                    ("Non Vegetarian", "Non Veg"),
                ],
                default="No Preference",
                max_length=128,
            ),
        ),
    ]
