# Generated by Django 4.1.1 on 2022-10-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0002_alter_customuser_first_name_alter_customuser_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email_confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
