# Generated by Django 4.1.1 on 2022-10-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "base",
            "0002_profile_profile_image_alter_customuser_first_name_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="profile_image",
        ),
        migrations.AddField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(
                default="default_profile_photo.jpg", upload_to="profile_pics"
            ),
        ),
    ]
