# Generated by Django 4.1.1 on 2022-10-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="visibility",
            field=models.BooleanField(default=True),
        ),
    ]
