# Generated by Django 4.1.1 on 2022-10-05 15:53

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_alter_profile_preference_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="profile",
            name="degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "Bachelors Program (BS)"),
                    ("M", "Masters Program (MS)"),
                    ("P", "Post Docterate (PHD)"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="diet",
            field=models.CharField(
                blank=True,
                choices=[("V", "Veg"), ("NV", "Non Veg")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("B", "Bachelors Program (BS)"),
                    ("M", "Masters Program (MS)"),
                    ("P", "Post Docterate (PHD)"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_diet",
            field=models.CharField(
                blank=True,
                choices=[("V", "Veg"), ("NV", "Non Veg")],
                max_length=5,
            ),
        ),
    ]
