# Generated by Django 4.1.1 on 2022-10-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_alter_profile_country_alter_profile_degree_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_profile_complete",
            field=models.BooleanField(default=False),
        ),
    ]
