# Generated by Django 4.1.1 on 2022-10-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_profile_is_profile_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("CS", "Computer Science"),
                    ("CE", "Computer Engg."),
                    ("EE", "Electrical Engg."),
                    ("MEC", "Mechanical Engg."),
                ],
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="preference_course",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N/A", "No Preference"),
                    ("CS", "Computer Science"),
                    ("CE", "Computer Engg."),
                    ("EE", "Electrical Engg."),
                    ("MEC", "Mechanical Engg."),
                ],
                max_length=5,
            ),
        ),
    ]
