# Generated by Django 4.1.1 on 2022-10-07 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_profile_course_profile_preference_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="hometown",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_degree",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N/A", "No Preference"),
                    ("B", "Bachelors Program (BS)"),
                    ("M", "Masters Program (MS)"),
                    ("P", "Post Docterate (PHD)"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_diet",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N/A", "No Preference"),
                    ("V", "Veg"),
                    ("NV", "Non Veg"),
                ],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="preference_gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("N/A", "No Preference"),
                    ("M", "Male"),
                    ("F", "Female"),
                    ("O", "Other"),
                ],
                max_length=5,
            ),
        ),
    ]
